version: '2'

services:
  redis:
    container_name: redis
    image: 'redis:7.2.1-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
    networks:
      - challenge-network

  website:
    build: .
    container_name: website
    restart: always
    command: >
      gunicorn -c "python:config.gunicorn" --reload "challenge.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/challenge'
    ports:
      - '8000:8000'
    networks:
      - challenge-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlpassword'
      MYSQL_DATABASE: 'challenge'
      MYSQL_USER: 'flask'
      MYSQL_PASSWORD: 'mysqlpassword'
    env_file:
      - '.env'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - challenge-network

  celery:
    build: .
    command: celery -A   challenge.service.fetch_service  worker --loglevel=INFO
    env_file:
      - '.env'
    volumes:
      - '.:/challenge'
    networks:
      - challenge-network
    depends_on:
      - mysql
      - redis


volumes:
  mysql:
  redis:

networks:
  challenge-network:
    driver: bridge

